//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationTestAJAX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licenses
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Serial { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> DataStart { get; set; }
        public Nullable<System.DateTime> DataEnd { get; set; }
        public int CompanysId { get; set; }
        public int TownsId { get; set; }
    
        public virtual Companys Companys { get; set; }
        public virtual Towns Towns { get; set; }
    }
}
