//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationTestAJAX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseTestAJAXEntities : DbContext
    {
        public DatabaseTestAJAXEntities()
            : base("name=DatabaseTestAJAXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Companys> Companys { get; set; }
        public virtual DbSet<Licenses> Licenses { get; set; }
        public virtual DbSet<Towns> Towns { get; set; }
    }
}
